### ISSUE TITLE
Unable to locate Java 7 or Java 8 Installer

### ISSUE THREAD

**Issue by Sanjeet01** [kibatic/docker-single-node-hadoop#2]
Docker file needs fix, as it is failing with below error. 
#7 39.64 E: Unable to locate package oracle-java8-installer
#7 39.64 E: Unable to locate package oracle-java8-set-default

![image](https://user-images.githubusercontent.com/52296153/142713469-cbebd669-65a5-465a-a6f1-4a9f99691bbd.png)

**Comment by philippe-levan** [comment]
fixed by PR https://github.com/kibatic/docker-single-node-hadoop/pull/1
